---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
output: 
    word_document: 
      reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        keep_tex: FALSE
    includes:
      in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
params: 
  species: "Snow crab"
  title: "&&species spatial patterns in the NMFS trawl survey" 
  dataPath: "./"
  strataFile: ""
  haulFiles: ""
  strataType: "2015"
  minYr: 2016
  maxYr: 2017
  HaulTypes: NULL
  sex: "ALL"
  maturity: "ALL"
  shell_condition: "ALL"
  calcMaleMaturity: FALSE
  aggBySex: FALSE
  aggByMaturity: FALSE
  aggByShellCondition: FALSE
  minSize: 0
  maxSize: '`r Inf`'
  verbosity: 0
title: '`r gsub("&&species",params$species,params$title,fixed=TRUE)`'
fontsize: 11pt
---

```{r init.CalcCPUE.Surveys.NMFS,echo=FALSE,results='hide'}
  ##set knitr options for subsequent chunks
  knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE)
```

```{r inputs.CalcCPUE.Surveys.NMFS}
  crabType<-NULL;
  dfr.SD<-NULL; dfr.HD<-NULL; dfr.ID<-NULL;
  dfrCPUE.ByXMS<-NULL; evs.csv<-NULL;
  if (exists("inputs")){
    message("in calcCPUE.Surveys.NMFS.Rmd.\n--'inputs' list exists.\n");
    yrs<-params$minYr:params$maxYr;
    crabType<-inputs$crabType;
    if (!is.null(inputs$dfr.SD)){ 
      message("--extracting dfr.SD from inputs list\n");
      dfr.SD<-inputs$dfr.SD;
      dfr.SD<-dfr.SD[dfr.SD$YEAR %in% yrs,];
    }
    if (!is.null(inputs$dfr.HD)){
      message("--extracting dfr.HD from inputs list\n");
      dfr.HD<-inputs$dfr.HD;
      dfr.HD<-dfr.HD[dfr.HD$YEAR %in% yrs,];
    }
    if (!is.null(inputs$dfr.ID)){ 
      message("--extracting dfr.ID from inputs list\n");
      dfr.ID<-inputs$dfr.ID;
      dfr.ID<-dfr.ID[dfr.ID$YEAR %in% yrs,,];
    }
    if (!is.null(inputs$dfrCPUE.ByXMS)) {
      message("--extracting dfrCPUE.ByXMS from inputs list\n");
      dfrCPUE.ByXMS<-inputs$dfrCPUE.ByXMS;
      dfrCPUE.ByXMS<-dfrCPUE.ByXMS[dfrCPUE.ByXMS$YEAR %in% yrs,];
    }
    if (!is.null(inputs$evs.csv)) {
      message("extracting evs.csv from inputs list\n");
      evs.csv<-inputs$evs.csv;
      evs.csv<-evs.csv[evs.csv$YEAR %in% yrs,];
    }
  }

  if (params$calcMaleMaturity){
    cat(paste0(" Note that categorization of mmale maturity is based on an ogive",
               " developed by Rugolo and Turnock, and is shown here for comparative purposes.\n"));
  }
  fn.SD<-file.path(params$dataPath,params$strataFile);
  fn.CH<-file.path(params$dataPath,params$haulFiles);
    
  if (is.null(crabType)){
    ##determine crab type
    if (tolower(params$species)=="tanner crab") {species<-"BTC"; crabType<-"Tanner crab";}    else
    if (tolower(params$species)=="snow crab")   {species<-"OTC"; crabType<-"snow crab";}      else
    if (tolower(params$species)=="BKC")         {species<-"BKC"; crabType<-"blue king crab";} else
    if (tolower(params$species)=="RKC")         {species<-"RKC"; crabType<-"red king crab";}
  }

  verbosity<-params$verbosity;##0=off,1=minimal,2=full
  
  ##required packages
  require(tcsamSurveyData);

  ##required preliminary calculations
  codes.TS<-Codes.TrawlSurvey();
```

```{r getStrata.CalcCPUE.Surveys.NMFS}
      message("Reading crab haul files.\n");
    if (is.null(dfr.SD)){
      ##read strata definitions
      message("Reading strata definitions file.\n");
      csvStrata<-read.csv(fn.SD,check.names=FALSE,stringsAsFactors=FALSE)[,1:8];
      ##select strata and stations
      dfr.SD<-selectStrata.TrawlSurvey(csvStrata,
                                       species=species,
                                       strataType=params$strataType,
                                       export=FALSE,
                                       verbosity=verbosity);
      rm(csvStrata);
    }
```

```{r readDataFiles.CalcCPUE.Surveys.NMFS}
    if (is.null(dfr.HD)|is.null(dfr.ID)){
      message("Reading crab haul files.\n");
      #load crabhaul files
      csvCrabhauls<-NULL;
      for (f in fn.CH){
        tmp<-read.csv(file=f,check.names=FALSE,stringsAsFactors=FALSE);
        csvCrabhauls<-rbind(csvCrabhauls,tmp);
        rm(tmp);
      }
      rm(f);
    }
```

```{r getHauls.CalcCPUE.Surveys.NMFS}
    if (is.null(dfr.HD)){
      ##select haul data
      message("Selecting haul data.\n");
      dfr.HD<-selectHauls.TrawlSurvey(dfr.SD,
                                      tbl=csvCrabhauls,
                                      YearRange=c(params$minYr,params$maxYr),
                                      export=FALSE,
                                      verbosity=verbosity);
    }
```

```{r getIndivs.CalcCPUE.Surveys.NMFS}
    if (is.null(dfr.ID)){
      #select individuals
      message("Selecting individuals.\n");
      dfr.ID<-selectIndivs.TrawlSurvey(dfr.HD,
                                       tbl=csvCrabhauls,
                                       sex=params$sex,
                                       shell_condition=params$shell_condition,
                                       maturity=params$maturity,
                                       calcMaleMaturity=params$calcMaleMaturity,
                                       minSize=params$minSize,
                                       maxSize=params$maxSize,
                                       export=FALSE,
                                       verbosity=verbosity);
      rm(csvCrabHauls);
    }
```

```{r calc.CalcCPUE.Surveys.NMFS}
    if (is.null(dfrCPUE.ByXMS)){
      message("Calculating CPUE.\n");
      ##calculate CPUE by haul
      dfrCPUE.ByXMS<-calcCPUE.ByHaul(dfr.HD,
                                    dfr.ID,
                                    bySex=!params$aggBySex,
                                    byMaturity=!params$aggByMaturity,
                                    byShellCondition=!params$aggByShellCondition,
                                    bySize=FALSE,
                                    export=FALSE,
                                    verbosity=verbosity);
  
      ##calculate CPUE by station
      dfrCPUE.ByXMS<-calcCPUE.ByStation(dfr.SD,
                                         dfrCPUE.ByXMS,
                                         export=FALSE,
                                         verbosity=verbosity);
  
  		##drop levels
  		dfrCPUE.ByXMS<-wtsUtilities::dropLevels(
                       dfrCPUE.ByXMS,
                       list(SEX=c('MISSING',"HERMAPHRODITIC"))
                     );
  
      ##label aggregated factor levels
      if (params$aggBySex)            dfrCPUE.ByXMS$SEX            <-"ALL";
      if (params$aggByMaturity)       dfrCPUE.ByXMS$MATURITY       <-"ALL";
      if (params$aggByShellCondition) dfrCPUE.ByXMS$SHELL_CONDITION<-"ALL";
    }
```

```{r extractEnvVars.CalcCPUE.Surveys.NMFS}
  if (is.null(evs.csv)) {
    ##calculate environmental data
    message("Calculating environmental data.\n");
    evs.csv<-calcEnvData.ByStation(dfr.SD,dfr.HD,verbosity=verbosity);
  }
```

