---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
output: 
    word_document: 
      reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        keep_tex: FALSE
    includes:
      in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
params: 
  species: "Snow crab"
  cpueType: "biomass"
  title: "&&species spatial patterns in the NMFS trawl survey" 
  outPath: "./"
  dataPath: "./"
  strataFile: ""
  haulFiles: ""
  gisPath: NULL
  strataType: "2015"
  minYr: 2016
  maxYr: 2017
  HaulTypes: NULL
  sex: "ALL"
  maturity: "ALL"
  shell_condition: "ALL"
  aggBySex: FALSE
  aggByMaturity: FALSE
  aggByShellCondition: FALSE
  minSize: 0
  maxSize: '`r Inf`'
  verbosity: 0
title: '`r gsub("&&species",params$species,params$title,fixed=TRUE)`'
fontsize: 11pt
---

```{r,echo=FALSE,results='hide'}
##set knitr options for subsequent chunks
knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE, fig.width=6.5, fig.height=7, dpi=300)
```

```{r inputs}
  fn.SD<-file.path(params$dataPath,params$strataFile);
  fn.CH<-file.path(params$dataPath,params$haulFiles);
    
  gisDir<-params$gisPath;

  outDir<-params$outPath;
  if (!dir.exists(outDir)) dir.create(outDir);

  ##determine crab type
  if (tolower(params$species)=="tanner crab") {species<-"BTC"; crabType<-"Tanner crab";}    else
  if (tolower(params$species)=="snow crab")   {species<-"OTC"; crabType<-"snow crab";}      else
  if (tolower(params$species)=="BKC") {species<-"BKC"; crabType<-"blue king crab";} else
  if (tolower(params$species)=="RKC") {species<-"RKC"; crabType<-"red king crab";}

  verbosity<-params$verbosity;##0=off,1=minimal,2=full
  
  ##required packages
  require(tcsamSurveyData);
  require(ggpubr);

  ##required preliminary calculations
  codes.TS<-Codes.TrawlSurvey();
```

#Introduction

This report creates a time series of maps of `r crabType` CPUE and bottom temperature from the NMFS EBS bottom trawl survey. 

\setcounter{tocdepth}{3}

\addcontentsline{toc}{section}{List of Tables in Model Comparisons}
\listoftables

\addcontentsline{toc}{section}{List of Figures in Model Comparisons}
\listoffigures

\newpage

```{r child="calcCPUE.Surveys.NMFS.Rmd"}
```

\newpage

```{r child="mapCPUE.Surveys.NMFS.Rmd"}
```

